[[colors.indexed_colors]]
color = "0xf99b15"
index = 16

[[colors.indexed_colors]]
color = "0xe96ba8"
index = 17

[[colors.indexed_colors]]
color = "0x41323f"
index = 18

[[colors.indexed_colors]]
color = "0x4f424c"
index = 19

[[colors.indexed_colors]]
color = "0x8d8687"
index = 20

[[colors.indexed_colors]]
color = "0xb9b6b0"
index = 21

[colors.bright]
black = "0x776e71"
blue = "0x06b6ef"
cyan = "0x5bc4bf"
green = "0x48b685"
magenta = "0x815ba4"
red = "0xef6155"
white = "0xe7e9db"
yellow = "0xfec418"

[colors.cursor]
cursor = "0xa39e9b"
text = "0x2f1e2e"

[colors.normal]
black = "0x2f1e2e"
blue = "0x06b6ef"
cyan = "0x5bc4bf"
green = "0x48b685"
magenta = "0x815ba4"
red = "0xef6155"
white = "0xa39e9b"
yellow = "0xfec418"

[colors.primary]
background = "0x2f1e2e"
foreground = "0xa39e9b"

[env]
SHELL = "/opt/homebrew/bin/fish"

[font.normal]
family = "Hack Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[scrolling]
history = 0

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
