[env]
SHELL = "/opt/homebrew/bin/fish"

[font.normal]
family = "Monoisome"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[scrolling]
history = 0

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
